apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-platform

resources:
  - ../../base

patchesJson6902:
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: ai-platform-route
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: ai.despairdrivendevelopment.net
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: ai-platform-http-redirect
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: ai.despairdrivendevelopment.net

commonLabels:
  environment: production