apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - litellm.yaml
  - openwebui.yaml
  - tika.yaml
  - mcpo.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: ai-platform
